#!/usr/bin/env python3
"""Map song ids to their official jacket (cover) image URLs -> data/jackets.js.

Usage: python3 scripts/build_jackets.py --songlist <holo-dreams-songlist/output.json>
The song list (https://github.com/MinatoIsuki/holo-dreams-songlist) is scraped from the
official music page https://www.hololive-dreams.com/en/music; images are loaded from there.
"""
import argparse
import json
import os
import re
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def norm(x):
    x = unicodedata.normalize("NFKC", x).lower()
    return re.sub(r"[^0-9a-z぀-ヿ一-鿿]", "", x)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--songlist", required=True)
    args = ap.parse_args()
    src = json.load(open(args.songlist, encoding="utf-8"))["songs"]
    game = open(os.path.join(ROOT, "data", "game.js"), encoding="utf-8").read()
    songs = json.loads(game[game.index("=") + 1:].rstrip().rstrip(";"))["songs"]
    index = {}
    for s in songs:
        for t in (s["title"]["en"], s["title"]["ja"]):
            index.setdefault(norm(t), s["id"])
    out, missing = {}, []
    for x in src:
        sid = index.get(norm(x["name"]))
        if not sid:
            missing.append(x["name"])
            continue
        url = re.sub(r"[?&]w=\d+", "", x["jacket"])
        url = re.sub(r"[?&]h=\d+", "", url)
        url += ("&" if "?" in url else "?") + "w=384&h=384"
        out[sid] = url.replace("?&", "?")
    with open(os.path.join(ROOT, "data", "jackets.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_jackets.py. Jacket images (c) COVER Corp. / QualiArts, served by the official site.\n")
        f.write("window.HOLO_JACKETS = ")
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"{len(out)} jackets, {len(missing)} unmatched: {missing}")


if __name__ == "__main__":
    main()
