#!/usr/bin/env python3
"""Import card illustrations named "<holomem JP name>_<rarity>_<JP card title>.webp".

This is the naming used by the public GitHub repo holodreams123-afk/holodream (docs/cards):
    git clone --depth 1 https://github.com/holodreams123-afk/holodream
    python3 scripts/import_named_art.py holodream/docs/cards

For every card of this site that matches a file (and has no picture of that kind yet, unless
--force), it writes assets/art/full/<cardId>.webp (1024x576) and a square icon
assets/art/icon/<cardId>.webp (300x300, cropped from the upper middle of the illustration),
then rebuilds data/art.js.
Card art (c) QualiArts / COVER Corp.; for personal, non-commercial use.
"""
import argparse
import json
import os
import unicodedata

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_js(path):
    s = open(os.path.join(ROOT, path), encoding="utf-8").read()
    return json.loads(s[s.index("=") + 1:].rstrip().rstrip(";"))


def norm(s):
    s = unicodedata.normalize("NFKC", s or "")
    return "".join(ch for ch in s.lower() if ch.isalnum())


def icon_from(im):
    w, h = im.size
    side = int(h * 0.74)
    left = max(0, min(w - side, (w - side) // 2))
    top = int(h * 0.03)
    return im.crop((left, top, left + side, top + side)).resize((300, 300), Image.LANCZOS)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    data = load_js("data/cards.js")
    talents = data["talents"]
    files = {}
    for name in os.listdir(args.src):
        if not name.endswith(".webp") or name.count("_") < 2:
            continue
        who, rarity, title = name[:-5].split("_", 2)
        files[(norm(who), rarity, norm(title))] = os.path.join(args.src, name)
    art = {}
    for kind in ("icon", "vert", "full"):
        d = os.path.join(ROOT, "assets", "art", kind)
        os.makedirs(d, exist_ok=True)
        for f in os.listdir(d):
            if f.endswith(".webp"):
                art.setdefault(f[:-5], set()).add(kind)
    added = 0
    for c in data["cards"]:
        t = talents.get(c["chr"], {})
        names = {norm((t.get("name") or {}).get(k)) for k in ("ja", "en", "zh")}
        titles = {norm((c.get("title") or {}).get(k)) for k in ("ja", "en", "zh")}
        src = next((p for (who, r, title), p in files.items() if r == str(c["rarity"]) and who in names and title in titles), None)
        if not src:
            continue
        have = art.get(c["id"], set())
        im = Image.open(src).convert("RGB")
        if args.force or "full" not in have:
            im.resize((1024, round(1024 * im.size[1] / im.size[0])), Image.LANCZOS).save(
                os.path.join(ROOT, "assets", "art", "full", c["id"] + ".webp"), "WEBP", quality=82)
            art.setdefault(c["id"], set()).add("full")
            added += 1
        if args.force or "icon" not in have:
            icon_from(im).save(os.path.join(ROOT, "assets", "art", "icon", c["id"] + ".webp"), "WEBP", quality=85)
            art.setdefault(c["id"], set()).add("icon")
    with open(os.path.join(ROOT, "data", "art.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/import_art.py / download_images.py / import_named_art.py. Card art (c) QualiArts / COVER Corp.\n")
        f.write("window.HOLO_ART = ")
        json.dump({k: sorted(v) for k, v in sorted(art.items())}, f, separators=(",", ":"))
        f.write(";\n")
    missing = [c["id"] for c in data["cards"] if c["id"] not in art]
    print(f"added {added} illustrations; cards with a picture: {len(data['cards']) - len(missing)}/{len(data['cards'])}")
    for m in missing:
        print("  still missing:", m)


if __name__ == "__main__":
    main()
