#!/usr/bin/env python3
"""Copy card art into assets/art and write data/art.js (which cards have art).

Usage: python3 scripts/import_art.py --icons <dir> --full <dir>
Files must be named <cardId>.webp (e.g. card-00001-5-uniq-0000-00.webp).
  icons: square card icons (with the in-game frame) used on card tiles
  full:  wide card illustrations used in the card detail view
Card art © QualiArts / COVER Corp.
"""
import argparse
import json
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--icons")
    ap.add_argument("--full")
    args = ap.parse_args()
    art = {}
    for kind, src in (("icon", args.icons), ("full", args.full)):
        dst = os.path.join(ROOT, "assets", "art", kind)
        os.makedirs(dst, exist_ok=True)
        if src:
            for name in sorted(os.listdir(src)):
                if name.startswith("card-") and name.endswith(".webp"):
                    shutil.copyfile(os.path.join(src, name), os.path.join(dst, name))
        for name in os.listdir(dst):
            if name.endswith(".webp"):
                art.setdefault(name[:-5], []).append(kind)
    with open(os.path.join(ROOT, "data", "art.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/import_art.py. Card art (c) QualiArts / COVER Corp.\n")
        f.write("window.HOLO_ART = ")
        json.dump({k: sorted(v) for k, v in sorted(art.items())}, f, separators=(",", ":"))
        f.write(";\n")
    print(f"{len(art)} cards with art")


if __name__ == "__main__":
    main()
